spring.application.name=client2026ms
server.port=8080
client2026ms.greeting=Ciao
client2026ms.default-value=Mondo
#spring.config.import=optional:configserver:
spring.config.import=optional:configserver:http://127.0.0.1:8888
spring.cloud.config.uri=http://localhost:8888
management.endpoints.web.exposure.include=*